<a href="https://colab.research.google.com/github/JBadawood/Mathematical_Optimization/blob/main/%D8%A7%D9%84%D8%AC%D8%A8%D8%B1_%D8%A7%D9%84%D8%AE%D8%B7%D9%8A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **الجبر الخطي في علم البيانات**
https://www.coursera.org/learn/machine-learning-linear-algebra

\\
Linear Algebra: Basics - الجبر الخطي: أساسيات  
https://youtu.be/3SZosLWeUNU
> فيديو مبسط للجبر الخطي للـ د. إبراهيم المسلَّم

**AI (DNNs) | New Mathematics**  
The **[Modern Mathematics](https://arxiv.org/abs/2105.04026)** of Deep Learning ([The Mathematics of Artificial Intelligence](https://arxiv.org/abs/2203.08890) | Deep Neural Networks)

\
*الذكاء الاصطناعي هو الرياضيات الجديدة للعالم.*  
https://twitter.com/SDAIA_SA/status/1601631210090147840

\\
"Math isn’t about memorizing formulas; it’s about sharpening your intuition".  
https://twitter.com/luis_likes_math/status/1618989706511015936  
https://www.deeplearning.ai/courses/mathematics-for-machine-learning-and-data-science-specialization/

## **1- System of Linear Equations**

### 1-1 Introduction to NumPy Arrays

A Visual Intro to NumPy and Data Representation  
"The *NumPy package* is the workhorse of **data analysis**, **machine learning**, and **scientific computing** in the python ecosystem."  

"Some of python’s leading package rely on NumPy as a fundamental piece of their infrastructure (examples include scikit-learn, SciPy, **pandas**, and **tensorflow**)"  
https://jalammar.github.io/visual-numpy/  
https://twitter.com/JayAlammar/status/1313828008931852296

\\
**NumPy** (**Num**erical **Py**thon) is an open-source package that is widely used in science and engineering.

طبعًا مكتبة NumPy راح تساعدنا على التعامل بسهولة مع المتجهات (مصفوف عمود أو مصفوف سطر) والمصفوفات

\\
هنا راح ننشئ  
`2-D Arrays`



#### Import NumPy pakage

In [1]:
# أول شي نحتاج نثبت مكتبة NumPy
import numpy as np

In [2]:
# بهذه الطريقة أقدر أنشئ array بالقيم إلى أبغاها
data = np.array([1,2,3])

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
# عشان أحصل على أعلى قيمة في الـ array السابق
data.max()

3

In [8]:
# لو نبغى كل الثلاث قيم بواحد
ones = np.ones(3)
ones

array([1., 1., 1.])

In [6]:
# لو نبغاها بصفر راح نكتب التالي
np.zeros(3)

array([0., 0., 0.])

In [7]:
# أما إذا حابين نخليها 3 قيم عشوائية
np.random.random(3)

array([0.34197633, 0.93982218, 0.08841528])

In [26]:
# كذلك نقدر ننشئ وحدة بدون ما نحدد ايش الأرقام مبدئيًا
np.empty(3)

array([ 3.33333333,  6.66666667, 10.        ])

In [10]:
modified_data = data + ones
modified_data

array([2., 3., 4.])

In [11]:
# عشان أظهر وحدة من عناصر الـ array
modified_data[0]

2.0

In [12]:
# عشان أظهر جزء من البيانات وأعمل slice
modified_data[0:2]

array([2., 3.])

#### 1-D Array

In [15]:
np.array([0,1,2])

array([0, 1, 2])

 نقدر نعمل الـ array بطريقة ثانية

In [14]:
np.arange(3)

array([0, 1, 2])

In [16]:
# نقدر نحدد البداية والنهاية وكم يقفز العد
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

طريقة ثالثة بتحديد عدد العناصر في الـ array

In [18]:
# نحدد البداية والنهاية وكم عنصر
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
# نقدر نشيك على نوع البيانات
(np.linspace(0,10,5)).dtype

dtype('float64')

> نلاحظ أن نوع البيانات في الـ array السابق هو float  
نقدر نغيره لأعداد صحيحة

In [22]:
np.linspace(0,10,5,dtype=int)

array([ 0,  2,  5,  7, 10])

#### 2-D & Multidimensional Arrays (ndarray)

In [28]:
# 2-D array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# نقد نعيد تشكيل الـ one-dimensional array
one_D = np.array([1,2,3,4,5,6])

two_D = np.reshape(one_D, (2,3))

In [30]:
two_D

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# عشان نشوف الـ array هو كم بعد
two_D.ndim

2

In [32]:
# ولمعرفة عدد صفوف المصفوفة وعدد أعمدتها
two_D.shape

(2, 3)

In [33]:
# أما إذا نبغى نعرف عدد عناصر المصفوفة
two_D.size

6

### 1-2 Solving Linear Systems: 2 variables

## **2- Solving System of Linear Equations**

### 2-1 Solving Linear Systems: 3 variables

### 2-2 System of Linear Equations

## **3- Vectors & Linear Transformations**

### 3-1 Vector Operations: Scalar Multiplication, Sum and Dot Product of Vectors

### 3-2 Matrix Multiplication

### 3-3 Linear Transformations

### 3-4 Single Perceptron Neural Networks for Linear Regression

## **4- Determinants & Eigenvectors**

### 4-1 Eigenvalues and Eigenvectors